source 'https://rubygems.org'

ruby '2.6.6'
gem 'rails', '4.2.10'

gem 'sass-rails', '~> 5.0.3'
gem 'coffee-rails', '~> 4.1.0'
gem 'uglifier', '>= 2.7.1'

gem 'jquery-rails'
gem 'haml'
gem 'protected_attributes'
gem 'devise'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem "omniauth-rails_csrf_protection", "~> 1.0"
gem 'dotenv-rails'

group :development, :test do
  gem "sqlite3", "~> 1.3.6"
  gem 'byebug'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'launchy'
  gem 'rspec-rails'
  gem 'pry'
  gem 'pry-byebug'
  gem 'cucumber-rails' 
  gem 'cucumber-rails-training-wheels'
end

group :production do
  gem 'pg'
end
